pipeline {
    agent any
    stages {
        stage('cleanup stage') {
            steps {
                deleteDir() 
            }
        }
        stage('clone the repo') {
            steps {
                sh 'git clone https://github.com/madhukummari/simple-java-maven-app.git'

            }
        }
        stage('build') {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install -Denforcer.skip=true"
                }
            }
        }
        stage('test') {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
            }
        }
    }
  }
}
